Numpy 12/10/2023

In [ ]:
import numpy as np

In [ ]:
demo=[1,2,3,4] #list
demo

[1, 2, 3, 4]

In [ ]:
np.array(demo)

array([1, 2, 3, 4])

In [ ]:
my_matrix=[[1,2,3],
           [4,5,6],
           [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(4) #eye means identity matrix used to print ones diagonally

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(71,101,2) #odd numbers from 70 to 100

array([71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
np.arange(3,101,3) #to print tables

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
np.linspace(10,15,7) #to get equal parts of the range

array([10.        , 10.83333333, 11.66666667, 12.5       , 13.33333333,
       14.16666667, 15.        ])

In [ ]:
np.linspace(11,17,100) #to do equal parts of range

array([11.        , 11.06060606, 11.12121212, 11.18181818, 11.24242424,
       11.3030303 , 11.36363636, 11.42424242, 11.48484848, 11.54545455,
       11.60606061, 11.66666667, 11.72727273, 11.78787879, 11.84848485,
       11.90909091, 11.96969697, 12.03030303, 12.09090909, 12.15151515,
       12.21212121, 12.27272727, 12.33333333, 12.39393939, 12.45454545,
       12.51515152, 12.57575758, 12.63636364, 12.6969697 , 12.75757576,
       12.81818182, 12.87878788, 12.93939394, 13.        , 13.06060606,
       13.12121212, 13.18181818, 13.24242424, 13.3030303 , 13.36363636,
       13.42424242, 13.48484848, 13.54545455, 13.60606061, 13.66666667,
       13.72727273, 13.78787879, 13.84848485, 13.90909091, 13.96969697,
       14.03030303, 14.09090909, 14.15151515, 14.21212121, 14.27272727,
       14.33333333, 14.39393939, 14.45454545, 14.51515152, 14.57575758,
       14.63636364, 14.6969697 , 14.75757576, 14.81818182, 14.87878788,
       14.93939394, 15.        , 15.06060606, 15.12121212, 15.18

In [ ]:
np.random.rand(3) #to print random values

array([0.49853883, 0.47888212, 0.27825898])

In [ ]:
np.random.rand(4,4) #To print matrix using random values

array([[0.29904764, 0.57379187, 0.30227116, 0.27221963],
       [0.58721592, 0.6721549 , 0.99129278, 0.2133991 ],
       [0.8343062 , 0.58685708, 0.92664226, 0.51787602],
       [0.7849188 , 0.53716342, 0.75635587, 0.17576926]])

In [ ]:
np.random.randn(3,3)

array([[ 1.16918595,  1.06948141, -0.54370859],
       [-0.53532165,  0.35806402,  0.10617353],
       [-1.38187582,  0.96068305, -0.18464007]])

In [ ]:
np.random.randint(10,20,6) #Here 6 denotes count of numbers

array([15, 15, 11, 16, 17, 14])

In [ ]:
G= np.arange(10,20,2)
G

array([10, 12, 14, 16, 18])

In [ ]:
Abc=np.arange(1,10)
Abc

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Abc[5] #To find any number from array using index position

6

In [ ]:
Abc[4:9] #find number using index position

array([5, 6, 7, 8, 9])

In [ ]:
Abc[4:9:2]=10
Abc

array([ 1,  2,  3,  4, 10,  6, 10,  8, 10])

In [ ]:
Abc[1:10:3]=0
Abc

array([ 1,  0,  3,  4,  0,  6, 10,  0, 10])

In [ ]:
arr2d=np.arange(9).reshape(3,3) #reshape the matrix
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr2d[2][2]

8

In [ ]:
arr3d=np.random.randn(3,3,3) #count of matrix, No. of Rows, No. of Column
arr3d

array([[[ 0.92230291,  1.34507455, -2.14074061],
        [-1.35861902,  0.54304766,  1.50185448],
        [-0.31773261, -1.69374968, -0.18976604]],

       [[-1.28579323,  0.1602282 , -1.11000231],
        [ 0.41095471, -0.40087024,  0.12042614],
        [ 0.87108842,  0.48790547, -1.60140352]],

       [[ 0.83357041,  1.32281872,  0.45703677],
        [ 0.17178944,  0.33290325,  0.39328742],
        [-1.00210774, -0.32238245,  0.71548692]]])

In [ ]:
 arr2d[0:3,1:3]

array([[1, 2],
       [4, 5],
       [7, 8]])



> Panda



In [ ]:
import pandas as pd
import numpy as np

In [ ]:
names=pd.Series(['4.5','xyz'])
names


0    4.5
1    xyz
dtype: object

In [ ]:
names.values

array(['4.5', 'xyz'], dtype=object)

In [ ]:
names=pd.Series(['ABC','XYZ'],index=['comp','AIDS'])
names

comp    ABC
AIDS    XYZ
dtype: object

In [ ]:
names['AIDS']='LMN'
names

comp    ABC
AIDS    LMN
dtype: object



> CREATE A TABLE HAVING ATTRIBUTES 'MATHS','ENGLISH','PHYSICS',AND RECORDS AS STUDENT MARKS. ALSO ADD ONE MORE ATTIBUTE 'HISTORY' IN EXISTING TABLE.



In [ ]:
marks={'Maths':[56,36,45,85,96],
      'English':[45,63,96,87,45],
      'Physics':[96,85,78,96,78]}
marks=pd.DataFrame(marks)
marks

Maths  English  Physics
0     56       45       96
1     36       63       85
2     45       96       78
3     85       87       96
4     96       45       78

In [ ]:
marks=pd.DataFrame(marks,columns=['Maths','English','Physics','History'])
marks

Maths  English  Physics  History
0     56       45       96      NaN
1     36       63       85      NaN
2     45       96       78      NaN
3     85       87       96      NaN
4     96       45       78      NaN

In [ ]:
marks['History'] = [56,85,96,78,45]
marks

Maths  English  Physics  History
0     56       45       96       56
1     36       63       85       85
2     45       96       78       96
3     85       87       96       78
4     96       45       78       45



> CREATE A 5X5 MATRIX WITH RANDOM VALUES. ADD INDEX 'MONDAY','TUESDAY','WED','THU','FRI','SAT' AND COLUMS WILL BE 'A','B','C','D','E'.



In [ ]:
matrix=np.arange(25).reshape(5,5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
matrix=pd.DataFrame(matrix,columns=['A','B','C','D','E'] ,index=['Mon','Tue','web','Thu','Fri'])
matrix

A   B   C   D   E
Mon   0   1   2   3   4
Tue   5   6   7   8   9
web  10  11  12  13  14
Thu  15  16  17  18  19
Fri  20  21  22  23  24

# QUESTION 1 : Movies

> Upload the dataset of movie and find the following.
1. column names
2. values
3. datatypes
4. datatypes value counts
5. find movie director names
6. find sum of null values
7. find statistics of 'actor_1_facebook_likes'
8. add column 'actor_director_facebook_likes' which is sum of actors and directors likes
9. add column 'is_cast_likes_more' and fill it with booleanmm values if 'cast_total_facebook_likes' are greater than 'actor_director_facebook_likes'.



In [ ]:
df=pd.read_csv('/moviedataset.csv')
df

color      director_name  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0   
1     Color     Gore Verbinski                   302.0     169.0   
2     Color         Sam Mendes                   602.0     148.0   
3     Color  Christopher Nolan                   813.0     164.0   
4       NaN        Doug Walker                     NaN       NaN   
...     ...                ...                     ...       ...   
4911  Color        Scott Smith                     1.0      87.0   
4912  Color                NaN                    43.0      43.0   
4913  Color   Benjamin Roberds                    13.0      76.0   
4914  Color        Daniel Hsia                    14.0     100.0   
4915  Color           Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
4911                      2.0                   318.0     Daphne Zuniga   
4912                      NaN                   319.0     Valorie Curry   
4913                      0.0                     0.0     Maxwell Moody   
4914                      0.0                   489.0     Daniel Henney   
4915                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                    40000.0  309404152.0         Action|Adventure|Fantasy   
2                    11000.0  200074175.0        Action|Adventure|Thriller   
3                    27000.0  448130642.0                  Action|Thriller   
4                      131.0          NaN                      Documentary   
...                      ...          ...                              ...   
4911                   637.0          NaN                     Comedy|Drama   
4912                   841.0          NaN     Crime|Drama|Mystery|Thriller   
4913                     0.0          NaN            Drama|Horror|Thriller   
4914                   946.0      10443.0             Comedy|Drama|Romance   
4915                    86.0      85222.0                      Documentary   

      ... num_user_for_reviews language  country  content_rating       budget  \
0     ...               3054.0  English      USA           PG-13  237000000.0   
1     ...               1238.0  English      USA           PG-13  300000000.0   
2     ...                994.0  English       UK           PG-13  245000000.0   
3     ...               2701.0  English      USA           PG-13  250000000.0   
4     ...                  NaN      NaN      NaN             NaN          NaN   
...   ...                  ...      ...      ...             ...          ...   
4911  ...                  6.0  English   Canada             NaN          NaN   
4912  ...                359.0  English      USA           TV-14          NaN   
4913  ...                  3.0  English      USA             NaN       1400.0   
4914  ...                  9.0  English      USA           PG-13          NaN   
4915  ...                 84.0  English      USA              PG       1100.0   

      title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0         2009.0                  936.0        7.9          1.78   
1         2007.0                 5000.0        7.1          2.35   
2         2015.0                  393.0        6.8          2.35   
3         2012.0                23000.0        8.5          2.35   
4            NaN                   12.

In [ ]:
movies= (df.columns) #1 column names
movies


Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [ ]:
movies=(df.values) #2 values
movies

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

In [ ]:
movies=df.dtypes  #3 datatypes
movies

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
m

In [ ]:
movies=df.dtypes.value_counts()  #4 datatypes value counts
movies

float64    13
object     12
int64       3
dtype: int64

In [ ]:
movies=df.director_name #5find movie director names
movies

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...        
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [ ]:
movies=df.isnull()
movies

color  director_name  num_critic_for_reviews  duration  \
0     False          False                   False     False   
1     False          False                   False     False   
2     False          False                   False     False   
3     False          False                   False     False   
4      True          False                    True      True   
...     ...            ...                     ...       ...   
4911  False          False                   False     False   
4912  False           True                   False     False   
4913  False          False                   False     False   
4914  False          False                   False     False   
4915  False          False                   False     False   

      director_facebook_likes  actor_3_facebook_likes  actor_2_name  \
0                       False                   False         False   
1                       False                   False         False   
2                       False                   False         False   
3                       False                   False         False   
4                       False                    True         False   
...                       ...                     ...           ...   
4911                    False                   False         False   
4912                     True                   False         False   
4913                    False                   False         False   
4914                    False                   False         False   
4915                    False                   False         False   

      actor_1_facebook_likes  gross  genres  ...  num_user_for_reviews  \
0                      False  False   False  ...                 False   
1                      False  False   False  ...                 False   
2                      False  False   False  ...                 False   
3                      False  False   False  ...                 False   
4                      False   True   False  ...                  True   
...                      ...    ...     ...  ...                   ...   
4911                   False   True   False  ...                 False   
4912                   False   True   False  ...                 False   
4913                   False   True   False  ...                 False   
4914                   False  False   False  ...                 False   
4915                   False  False   False  ...                 False   

      language  country  content_rating  budget  title_year  \
0        False    False           False   False       False   
1        False    False           False   False       False   
2        False    False           False   False       False   
3        False    False           False   False       False   
4         True     True            True    True        True   
...        ...      ...             ...     ...         ...   
4911     False    False            True    True       False   
4912     False    False           False    True        True   
4913     False    False            True   False       False   
4914     False    False           False    True       False   
4915     False    False           False   False       False   

      actor_2_facebook_likes  imdb_score  aspect_ratio  movie_facebook_likes  
0                      False       False         False                 False  
1                      False       False         False                 False  
2                      False       False         False                 False  
3                      False       False         False                 False  
4                      False       False          True                 False  
...                      ...         ...           ...                   ...  
4911                   False       False          True                 False  
4912                   False       False         False                 False  
4913                   Fals

In [ ]:
movies=df.isnull().sum() #6 find sum of null values
movies

color                         19
director_name                102
num_critic_for_reviews        49
duration                      15
director_facebook_likes      102
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        862
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                152
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               300
budget                       484
title_year                   106
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 326
movie_facebook_likes           0
dtype: int64

In [ ]:
movies=df["actor_1_facebook_likes"].mean()  #7 find statistics of 'actor_1_facebook_likes', mean of one column
movies

6494.488490527602

In [ ]:
movies=df["actor_1_facebook_likes"].mode()  #7 find statistics of 'actor_1_facebook_likes', mode of one column
movies

0    1000.0
Name: actor_1_facebook_likes, dtype: float64

In [ ]:
movies=df["actor_1_facebook_likes"].median()  #7 find statistics of 'actor_1_facebook_likes', median of one column
movies

982.0

In [ ]:
movies=df["actor_1_facebook_likes"].count()  #count of one column
movies

4909

In [ ]:
movies=pd.DataFrame(df,columns=['director_name', 'num_critic_for_reviews', 'duration',     #method 1 to add new column in existing table
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes','actor_director_facebook_likes'])
movies

director_name  num_critic_for_reviews  duration  \
0         James Cameron                   723.0     178.0   
1        Gore Verbinski                   302.0     169.0   
2            Sam Mendes                   602.0     148.0   
3     Christopher Nolan                   813.0     164.0   
4           Doug Walker                     NaN       NaN   
...                 ...                     ...       ...   
4911        Scott Smith                     1.0      87.0   
4912                NaN                    43.0      43.0   
4913   Benjamin Roberds                    13.0      76.0   
4914        Daniel Hsia                    14.0     100.0   
4915           Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
4911                      2.0                   318.0     Daphne Zuniga   
4912                      NaN                   319.0     Valorie Curry   
4913                      0.0                     0.0     Maxwell Moody   
4914                      0.0                   489.0     Daniel Henney   
4915                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                    40000.0  309404152.0         Action|Adventure|Fantasy   
2                    11000.0  200074175.0        Action|Adventure|Thriller   
3                    27000.0  448130642.0                  Action|Thriller   
4                      131.0          NaN                      Documentary   
...                      ...          ...                              ...   
4911                   637.0          NaN                     Comedy|Drama   
4912                   841.0          NaN     Crime|Drama|Mystery|Thriller   
4913                     0.0          NaN            Drama|Horror|Thriller   
4914                   946.0      10443.0             Comedy|Drama|Romance   
4915                    86.0      85222.0                      Documentary   

         actor_1_name  ... language  country  content_rating       budget  \
0         CCH Pounder  ...  English      USA           PG-13  237000000.0   
1         Johnny Depp  ...  English      USA           PG-13  300000000.0   
2     Christoph Waltz  ...  English       UK           PG-13  245000000.0   
3           Tom Hardy  ...  English      USA           PG-13  250000000.0   
4         Doug Walker  ...      NaN      NaN             NaN          NaN   
...               ...  ...      ...      ...             ...          ...   
4911      Eric Mabius  ...  English   Canada             NaN          NaN   
4912      Natalie Zea  ...  English      USA           TV-14          NaN   
4913      Eva Boehnke  ...  English      USA             NaN       1400.0   
4914        Alan Ruck  ...  English      USA           PG-13          NaN   
4915      John August  ...  English      USA              PG       1100.0   

      title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0         2009.0                  936.0        7.9          1.78   
1         2007.0                 5000.0        7.1          2.35   
2         2015.0                  393.0        6.8          2.35   
3         2012.0                23000.0        8.5          2.35   
4            NaN                   12.0        7.1           NaN   
...          ...                    ...        ...           ...   
4911      2013.0                  470.

In [ ]:
movies = df.assign(actor_director_facebook_likes=None)    ##method2: 8. add column 'actor_director_facebook_likes' which is sum of actors and directors likes
movies

color      director_name  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0   
1     Color     Gore Verbinski                   302.0     169.0   
2     Color         Sam Mendes                   602.0     148.0   
3     Color  Christopher Nolan                   813.0     164.0   
4       NaN        Doug Walker                     NaN       NaN   
...     ...                ...                     ...       ...   
4911  Color        Scott Smith                     1.0      87.0   
4912  Color                NaN                    43.0      43.0   
4913  Color   Benjamin Roberds                    13.0      76.0   
4914  Color        Daniel Hsia                    14.0     100.0   
4915  Color           Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
4911                      2.0                   318.0     Daphne Zuniga   
4912                      NaN                   319.0     Valorie Curry   
4913                      0.0                     0.0     Maxwell Moody   
4914                      0.0                   489.0     Daniel Henney   
4915                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                    40000.0  309404152.0         Action|Adventure|Fantasy   
2                    11000.0  200074175.0        Action|Adventure|Thriller   
3                    27000.0  448130642.0                  Action|Thriller   
4                      131.0          NaN                      Documentary   
...                      ...          ...                              ...   
4911                   637.0          NaN                     Comedy|Drama   
4912                   841.0          NaN     Crime|Drama|Mystery|Thriller   
4913                     0.0          NaN            Drama|Horror|Thriller   
4914                   946.0      10443.0             Comedy|Drama|Romance   
4915                    86.0      85222.0                      Documentary   

      ... language country  content_rating       budget title_year  \
0     ...  English     USA           PG-13  237000000.0     2009.0   
1     ...  English     USA           PG-13  300000000.0     2007.0   
2     ...  English      UK           PG-13  245000000.0     2015.0   
3     ...  English     USA           PG-13  250000000.0     2012.0   
4     ...      NaN     NaN             NaN          NaN        NaN   
...   ...      ...     ...             ...          ...        ...   
4911  ...  English  Canada             NaN          NaN     2013.0   
4912  ...  English     USA           TV-14          NaN        NaN   
4913  ...  English     USA             NaN       1400.0     2013.0   
4914  ...  English     USA           PG-13          NaN     2012.0   
4915  ...  English     USA              PG       1100.0     2004.0   

      actor_2_facebook_likes imdb_score aspect_ratio  movie_facebook_likes  \
0                      936.0        7.9         1.78                 33000   
1                     5000.0        7.1         2.35                     0   
2                      393.0        6.8         2.35                 85000   
3                    23000.0        8.5         2.35                164000   
4                       12.0        7.1          NaN                     0   
...                      ...        ...   

In [ ]:
df['actor_director_facebook_likes'] = df['director_facebook_likes'] + df['actor_3_facebook_likes']+df['actor_1_facebook_likes']+df['actor_2_facebook_likes']
df    #8 sum of specific columns using rows

color      director_name  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0   
1     Color     Gore Verbinski                   302.0     169.0   
2     Color         Sam Mendes                   602.0     148.0   
3     Color  Christopher Nolan                   813.0     164.0   
4       NaN        Doug Walker                     NaN       NaN   
...     ...                ...                     ...       ...   
4911  Color        Scott Smith                     1.0      87.0   
4912  Color                NaN                    43.0      43.0   
4913  Color   Benjamin Roberds                    13.0      76.0   
4914  Color        Daniel Hsia                    14.0     100.0   
4915  Color           Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
4911                      2.0                   318.0     Daphne Zuniga   
4912                      NaN                   319.0     Valorie Curry   
4913                      0.0                     0.0     Maxwell Moody   
4914                      0.0                   489.0     Daniel Henney   
4915                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                    40000.0  309404152.0         Action|Adventure|Fantasy   
2                    11000.0  200074175.0        Action|Adventure|Thriller   
3                    27000.0  448130642.0                  Action|Thriller   
4                      131.0          NaN                      Documentary   
...                      ...          ...                              ...   
4911                   637.0          NaN                     Comedy|Drama   
4912                   841.0          NaN     Crime|Drama|Mystery|Thriller   
4913                     0.0          NaN            Drama|Horror|Thriller   
4914                   946.0      10443.0             Comedy|Drama|Romance   
4915                    86.0      85222.0                      Documentary   

      ... language country  content_rating       budget title_year  \
0     ...  English     USA           PG-13  237000000.0     2009.0   
1     ...  English     USA           PG-13  300000000.0     2007.0   
2     ...  English      UK           PG-13  245000000.0     2015.0   
3     ...  English     USA           PG-13  250000000.0     2012.0   
4     ...      NaN     NaN             NaN          NaN        NaN   
...   ...      ...     ...             ...          ...        ...   
4911  ...  English  Canada             NaN          NaN     2013.0   
4912  ...  English     USA           TV-14          NaN        NaN   
4913  ...  English     USA             NaN       1400.0     2013.0   
4914  ...  English     USA           PG-13          NaN     2012.0   
4915  ...  English     USA              PG       1100.0     2004.0   

      actor_2_facebook_likes imdb_score aspect_ratio  movie_facebook_likes  \
0                      936.0        7.9         1.78                 33000   
1                     5000.0        7.1         2.35                     0   
2                      393.0        6.8         2.35                 85000   
3                    23000.0        8.5         2.35                164000   
4                       12.0        7.1          NaN                     0   
...                      ...        ...   



> 9. add column 'is_cast_likes_more' and fill it with boolean values if 'cast_total_facebook_likes' are greater than 'actor_director_facebook_likes'.



In [ ]:
movies = df.assign(is_cast_likes_more=None)    #method2 add column 'is_cast_likes_more' and fill it with booleanmm values if 'cast_total_facebook_likes'
                                              #are greater than 'actor_director_facebook_likes'.
movies

color      director_name  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0   
1     Color     Gore Verbinski                   302.0     169.0   
2     Color         Sam Mendes                   602.0     148.0   
3     Color  Christopher Nolan                   813.0     164.0   
4       NaN        Doug Walker                     NaN       NaN   
...     ...                ...                     ...       ...   
4911  Color        Scott Smith                     1.0      87.0   
4912  Color                NaN                    43.0      43.0   
4913  Color   Benjamin Roberds                    13.0      76.0   
4914  Color        Daniel Hsia                    14.0     100.0   
4915  Color           Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
4911                      2.0                   318.0     Daphne Zuniga   
4912                      NaN                   319.0     Valorie Curry   
4913                      0.0                     0.0     Maxwell Moody   
4914                      0.0                   489.0     Daniel Henney   
4915                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                    40000.0  309404152.0         Action|Adventure|Fantasy   
2                    11000.0  200074175.0        Action|Adventure|Thriller   
3                    27000.0  448130642.0                  Action|Thriller   
4                      131.0          NaN                      Documentary   
...                      ...          ...                              ...   
4911                   637.0          NaN                     Comedy|Drama   
4912                   841.0          NaN     Crime|Drama|Mystery|Thriller   
4913                     0.0          NaN            Drama|Horror|Thriller   
4914                   946.0      10443.0             Comedy|Drama|Romance   
4915                    86.0      85222.0                      Documentary   

      ... country content_rating       budget  title_year  \
0     ...     USA          PG-13  237000000.0      2009.0   
1     ...     USA          PG-13  300000000.0      2007.0   
2     ...      UK          PG-13  245000000.0      2015.0   
3     ...     USA          PG-13  250000000.0      2012.0   
4     ...     NaN            NaN          NaN         NaN   
...   ...     ...            ...          ...         ...   
4911  ...  Canada            NaN          NaN      2013.0   
4912  ...     USA          TV-14          NaN         NaN   
4913  ...     USA            NaN       1400.0      2013.0   
4914  ...     USA          PG-13          NaN      2012.0   
4915  ...     USA             PG       1100.0      2004.0   

     actor_2_facebook_likes  imdb_score aspect_ratio movie_facebook_likes  \
0                     936.0         7.9         1.78                33000   
1                    5000.0         7.1         2.35                    0   
2                     393.0         6.8         2.35                85000   
3                   23000.0         8.5         2.35               164000   
4                      12.0         7.1          NaN                    0   
...                     ...         ...          ...                  ...   
4911                  470.0         7.7          NaN                   84   
49

In [ ]:
df['is_cast_likes_more'] = df['cast_total_facebook_likes'] > df['actor_director_facebook_likes']
df

color      director_name  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0   
1     Color     Gore Verbinski                   302.0     169.0   
2     Color         Sam Mendes                   602.0     148.0   
3     Color  Christopher Nolan                   813.0     164.0   
4       NaN        Doug Walker                     NaN       NaN   
...     ...                ...                     ...       ...   
4911  Color        Scott Smith                     1.0      87.0   
4912  Color                NaN                    43.0      43.0   
4913  Color   Benjamin Roberds                    13.0      76.0   
4914  Color        Daniel Hsia                    14.0     100.0   
4915  Color           Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
4911                      2.0                   318.0     Daphne Zuniga   
4912                      NaN                   319.0     Valorie Curry   
4913                      0.0                     0.0     Maxwell Moody   
4914                      0.0                   489.0     Daniel Henney   
4915                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                    40000.0  309404152.0         Action|Adventure|Fantasy   
2                    11000.0  200074175.0        Action|Adventure|Thriller   
3                    27000.0  448130642.0                  Action|Thriller   
4                      131.0          NaN                      Documentary   
...                      ...          ...                              ...   
4911                   637.0          NaN                     Comedy|Drama   
4912                   841.0          NaN     Crime|Drama|Mystery|Thriller   
4913                     0.0          NaN            Drama|Horror|Thriller   
4914                   946.0      10443.0             Comedy|Drama|Romance   
4915                    86.0      85222.0                      Documentary   

      ... country content_rating       budget  title_year  \
0     ...     USA          PG-13  237000000.0      2009.0   
1     ...     USA          PG-13  300000000.0      2007.0   
2     ...      UK          PG-13  245000000.0      2015.0   
3     ...     USA          PG-13  250000000.0      2012.0   
4     ...     NaN            NaN          NaN         NaN   
...   ...     ...            ...          ...         ...   
4911  ...  Canada            NaN          NaN      2013.0   
4912  ...     USA          TV-14          NaN         NaN   
4913  ...     USA            NaN       1400.0      2013.0   
4914  ...     USA          PG-13          NaN      2012.0   
4915  ...     USA             PG       1100.0      2004.0   

     actor_2_facebook_likes  imdb_score aspect_ratio movie_facebook_likes  \
0                     936.0         7.9         1.78                33000   
1                    5000.0         7.1         2.35                    0   
2                     393.0         6.8         2.35                85000   
3                   23000.0         8.5         2.35               164000   
4                      12.0         7.1          NaN                    0   
...                     ...         ...          ...                  ...   
4911                  470.0         7.7          NaN                   84   
49

# QUESTION 2

> Slicing AND INDEXING



In [ ]:
df1=pd.read_csv('/sample_data.csv' ,index_col=0) #Load dataset
df1

state  color    food  age  height  score
Jane         NY   blue   Steak   30     165    4.6
Niko         TX  green    Lamb    2      70    8.3
Aaron        FL    red   Mango   12     120    9.0
Penelope     AL  white   Apple    4      80    3.3
Dean         AK   gray  Cheese   32     180    1.8
Christina    TX  black   Melon   33     172    9.5
Cornelia     TX    red   Beans   69     150    2.2

In [ ]:
df1.loc['Dean']

state         AK
color       gray
food      Cheese
age           32
height       180
score        1.8
Name: Dean, dtype: object

In [ ]:
df1['food']

Jane          Steak
Niko           Lamb
Aaron         Mango
Penelope      Apple
Dean         Cheese
Christina     Melon
Cornelia      Beans
Name: food, dtype: object

In [ ]:
df1[['state','color','food']]

state  color    food
Jane         NY   blue   Steak
Niko         TX  green    Lamb
Aaron        FL    red   Mango
Penelope     AL  white   Apple
Dean         AK   gray  Cheese
Christina    TX  black   Melon
Cornelia     TX    red   Beans

In [ ]:
df1.loc['Jane':'Penelope':2,'color':'height':2]


color  age
Jane   blue   30
Aaron   red   12

In [ ]:
df1.loc['Niko': :6 ,'food':'height':2]

food  height
Niko  Lamb      70

In [ ]:
 df1.loc['Niko': :6,'color': :5 ]

color
Niko  green

In [ ]:
df1.iloc[0:4,1:5:3]

color  height
Jane       blue     165
Niko      green      70
Aaron       red     120
Penelope  white      80

In [ ]:
df1.iloc[1: ,:-1]

state  color    food  age  height
Niko         TX  green    Lamb    2      70
Aaron        FL    red   Mango   12     120
Penelope     AL  white   Apple    4      80
Dean         AK   gray  Cheese   32     180
Christina    TX  black   Melon   33     172
Cornelia     TX    red   Beans   69     150

In [ ]:
df1.iloc[0: ,1: ]

color    food  age  height  score
Jane        blue   Steak   30     165    4.6
Niko       green    Lamb    2      70    8.3
Aaron        red   Mango   12     120    9.0
Penelope   white   Apple    4      80    3.3
Dean        gray  Cheese   32     180    1.8
Christina  black   Melon   33     172    9.5
Cornelia     red   Beans   69     150    2.2

In [ ]:
df1.iloc[4: :8 ,2: :9]

food
Dean  Cheese

# QUESTION 3

> COMPARISON OPERATORS AND CRITERIA



In [ ]:
df2=pd.read_csv('/stackoverflow_qa.csv')
df2

id         creationdate  score  viewcount  \
0       5486226  2011-03-30 12:26:50      4       2113   
1       5515021  2011-04-01 14:50:44      8       7015   
2       5558607  2011-04-05 21:13:50      2       7392   
3       6467832  2011-06-24 12:31:45      9      13056   
4       7577546  2011-09-28 01:58:38      9       2488   
...         ...                  ...    ...        ...   
56393  47606711  2017-12-02 10:07:13      0         17   
56394  47607549  2017-12-02 11:41:59     -1         41   
56395  47609325  2017-12-02 15:16:26      0         33   
56396  47609598  2017-12-02 15:45:40      2         18   
56397  47611969  2017-12-02 19:59:09     -6         19   

                                                   title  answercount  \
0                               Rolling median in python            3   
1           Compute a compounded return series in Python            3   
2            Sort a pandas DataMatrix in ascending order            2   
3      How to get the correlation between two timeser...            1   
4      Using pandas, how do I subsample a large DataF...            1   
...                                                  ...          ...   
56393                              slow loop using panda            1   
56394      Convert Numeric percentage values into String            1   
56395  Filtering for criteria in Pandas Dataframe Python            2   
56396  Python Multi index function with order preserv...            1   
56397            Converting Pandas Dataframe to R object            0   

       commentcount  favoritecount      quest_name  quest_rep  \
0                 4            1.0         yueerhu      125.0   
1                 6            7.0  Jason Strimpel     3301.0   
2                 0            1.0  Jason Strimpel     3301.0   
3                 0            7.0      user814005      117.0   
4                 0            5.0    Uri Laserson      958.0   
...             ...            ...             ...        ...   
56393             1            NaN            xxyy        3.0   
56394             2            NaN           Ajeet        1.0   
56395             4            NaN            NthA        1.0   
56396             0            NaN         Fan LUO       13.0   
56397             0            NaN   Soorya Paturi        1.0   

              ans_name  ans_rep  
0      Mike Pennington  26995.0  
1      Mike Pennington  26995.0  
2         Wes McKinney  43310.0  
3         Wes McKinney  43310.0  
4                 HYRY  54137.0  
...                ...      ...  
56393        user32185    308.0  
56394              NaN      NaN  
56395              NaN      NaN  
56396          erocoar    209.0  
56397              NaN      NaN  

[56398 rows x 12 columns]

In [ ]:
criteria=df2['viewcount']>=45678
criteria.head(20)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: viewcount, dtype: bool

In [ ]:
criteria=df2['id']>=5000000
criteria.head(20)

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
Name: id, dtype: bool

In [ ]:
criteria=df2['id']<=5000000
criteria.head(20)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: id, dtype: bool

In [ ]:
criteria1=df2['score'] >= 5
criteria1



0        False
1         True
2        False
3         True
4         True
         ...  
56393    False
56394    False
56395    False
56396    False
56397    False
Name: score, Length: 56398, dtype: bool

In [ ]:
criteria2=df2['ans_name']=='Scott Boston'
criteria2

0        False
1        False
2        False
3        False
4        False
         ...  
56393    False
56394    False
56395    False
56396    False
56397    False
Name: ans_name, Length: 56398, dtype: bool

In [ ]:
criteria_all = criteria1 & criteria2
df2[criteria_all]


id         creationdate  score  viewcount  \
38246  43209525  2017-04-04 14:03:17      5        131   
38640  42870703  2017-03-18 05:06:22      5        125   
44358  45064916  2017-07-12 18:16:49      5        428   
44814  44877663  2017-07-03 04:07:59      9       1267   
52013  47061564  2017-11-01 18:40:36      5         60   

                                                   title  answercount  \
38246          Pandas: Optimal way to MultiIndex columns            2   
38640  Simultaneous operation of groupby and resample...            1   
44358  How to find the correlation between a group of...            2   
44814       Error: float object has no attribute notnull            3   
52013  How to create strings from dataframe columns e...            5   

       commentcount  favoritecount    quest_name  quest_rep      ans_name  \
38246             0            0.0  sparc_spread     5470.0  Scott Boston   
38640             0            1.0   S. Naribole       43.0  Scott Boston   
44358             5            NaN           BKS      506.0  Scott Boston   
44814             2            1.0   Vivian  Tio      181.0  Scott Boston   
52013             0            NaN  hernanavella     1890.0  Scott Boston   

       ans_rep  
38246  23611.0  
38640  23611.0  
44358  23611.0  
44814  23611.0  
52013  23611.0

# QUESTION 4

> Upload the data set food_inspections.
1. Select the rows for the restaurants WILD GOOSE BAR & GRILL and TAQUERIA HACIENDA TAPATIA along with column Risk and Results.
2. What is the risk of restaurant SCRUB A DUB.
3. Select all columns from the 500th restaurant to the 510th.
4. Select restaurants 100,1000 and 10000 along with columns 5,3, and 1.


In [ ]:
df3=pd.read_csv('/food_inspections.csv',index_col=0)
df3

Facility Type             Risk  \
DBA Name                                                    
DANY'S TACOS                  Restaurant    Risk 1 (High)   
BILLY FOOD MARKET INC                NaN     Risk 3 (Low)   
TAQUERIA HACIENDA TAPATIA     Restaurant    Risk 1 (High)   
WILD GOOSE BAR & GRILL        Restaurant    Risk 1 (High)   
PUBLICAN TAVERN K1            Restaurant    Risk 1 (High)   
...                                  ...              ...   
FRESH PANTRY               Grocery Store  Risk 2 (Medium)   
BUTTER                               NaN     Risk 3 (Low)   
SAFAH FOOD & LIQUOR INC    Grocery Store     Risk 3 (Low)   
RAINBOW GROCERY            Grocery Store     Risk 3 (Low)   
MAKIA FOOD                           NaN     Risk 3 (Low)   

                                          Address      Zip Inspection Date  \
DBA Name                                                                     
DANY'S TACOS                 2857 S ST LOUIS AVE   60623.0      03/27/2017   
BILLY FOOD MARKET INC        3906 W ROOSEVELT RD   60624.0      03/27/2017   
TAQUERIA HACIENDA TAPATIA         4125 W 26TH ST   60623.0      03/27/2017   
WILD GOOSE BAR & GRILL        4265 N LINCOLN AVE   60618.0      03/27/2017   
PUBLICAN TAVERN K1             11601 W TOUHY AVE   60666.0      03/27/2017   
...                                           ...      ...             ...   
FRESH PANTRY               7337 S SOUTH SHORE DR   60649.0      01/06/2010   
BUTTER                            130 S GREEN ST   60607.0      01/06/2010   
SAFAH FOOD & LIQUOR INC        7105 S RACINE AVE   60636.0      01/05/2010   
RAINBOW GROCERY                   2003 W 69TH ST   60636.0      01/05/2010   
MAKIA FOOD                 2458 S CALIFORNIA AVE   60608.0      01/05/2010   

                                 Inspection Type    Results  \
DBA Name                                                      
DANY'S TACOS                             License       Fail   
BILLY FOOD MARKET INC                    License  Not Ready   
TAQUERIA HACIENDA TAPATIA  License Re-Inspection       Pass   
WILD GOOSE BAR & GRILL                   Canvass       Fail   
PUBLICAN TAVERN K1                       Canvass       Fail   
...                                          ...        ...   
FRESH PANTRY                           Complaint       Pass   
BUTTER                           Out of Business       Pass   
SAFAH FOOD & LIQUOR INC    Canvass Re-Inspection       Pass   
RAINBOW GROCERY            Canvass Re-Inspection       Pass   
MAKIA FOOD                 License Re-Inspection       Pass   

                                                                  Violations  
DBA Name                                                                      
DANY'S TACOS               16. FOOD PROTECTED DURING STORAGE, PREPARATION...  
BILLY FOOD MARKET INC                                                    NaN  
TAQUERIA HACIENDA TAPATIA  2. FACILITIES TO MAINTAIN PROPER TEMPERATURE -...  
WILD GOOSE BAR & GRILL     16. FOOD PROTECTED DURING STORAGE, PREPARATION...  
PUBLICAN TAVERN K1         18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...  
...                                                                      ...  
FRESH PANTRY               34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...  
BUTTER                                                                   NaN  
SAFAH FOOD & LIQUOR INC    18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...  
RAINBOW GROCERY            18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...  
MAKIA FOOD                 33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...  

[24063 rows x 8 columns]

In [ ]:
df3.loc['TAQUERIA HACIENDA TAPATIA':'WILD GOOSE BAR & GRILL','Risk':'Results':5] #1 Select the rows for the restaurants WILD GOOSE BAR & GRILL and TAQUERIA HACIENDA TAPATIA along with column Risk and Results.


Risk Results
DBA Name                                        
TAQUERIA HACIENDA TAPATIA  Risk 1 (High)    Pass
WILD GOOSE BAR & GRILL     Risk 1 (High)    Fail

In [ ]:
df3.columns

Index(['Facility Type', 'Risk', 'Address', 'Zip', 'Inspection Date',
       'Inspection Type', 'Results', 'Violations'],
      dtype='object')

In [ ]:
df3.loc[['SCRUB A DUB']]

Facility Type             Risk                Address      Zip  \
DBA Name                                                                     
SCRUB A DUB           NaN  Risk 2 (Medium)  3333 W FULLERTON AVE   60647.0   

            Inspection Date Inspection Type Results Violations  
DBA Name                                                        
SCRUB A DUB      01/07/2010         Canvass    Pass        NaN

In [ ]:
df3.loc['SCRUB A DUB','Risk': :7]

Risk    Risk 2 (Medium)
Name: SCRUB A DUB, dtype: object

In [ ]:
df3.loc['SCRUB A DUB':'SCRUB A DUB','Risk': :7]   #2 What is the risk of restaurant SCRUB A DUB.

Risk
DBA Name                    
SCRUB A DUB  Risk 2 (Medium)

In [ ]:
#3 Select all columns from the 500th restaurant to the 510th.
df3.iloc[500:511]

Facility Type             Risk  \
DBA Name                                                           
THE MECCA RESTAURANT                 Restaurant    Risk 1 (High)   
L & T CHINA FAST WOK INC.            Restaurant    Risk 1 (High)   
SCHNEIDER  SENIOR  APARTMENT       Golden Diner    Risk 1 (High)   
ECKHARDT CAFE                        Restaurant    Risk 1 (High)   
WING ZONE                            Restaurant    Risk 1 (High)   
ARBYS                                Restaurant    Risk 1 (High)   
LAS ISLAS MARIAS                     Restaurant    Risk 1 (High)   
MARGARET'S                           Restaurant    Risk 1 (High)   
POPEYES FAMOUS FRIED CHICKEN         Restaurant  Risk 2 (Medium)   
PJ PIZZA COMPANY 1 DBA PAPA JOHNS    Restaurant  Risk 2 (Medium)   
DUNKIN DONUTS                        Restaurant  Risk 2 (Medium)   

                                                   Address      Zip  \
DBA Name                                                              
THE MECCA RESTAURANT                 6666 N NORTHWEST HWY   60631.0   
L & T CHINA FAST WOK INC.           2020 N CALIFORNIA AVE   60647.0   
SCHNEIDER  SENIOR  APARTMENT          1750 W PETERSON AVE   60660.0   
ECKHARDT CAFE                            5640 S ELLIS AVE   60637.0   
WING ZONE                                  1757 W 87TH ST   60620.0   
ARBYS                                    500 W MADISON ST   60661.0   
LAS ISLAS MARIAS                   8205-8209 S PULASKI RD   60652.0   
MARGARET'S                          5134 W IRVING PARK RD   60641.0   
POPEYES FAMOUS FRIED CHICKEN         9516 S VINCENNES AVE   60643.0   
PJ PIZZA COMPANY 1 DBA PAPA JOHNS          1755 W 87TH ST   60620.0   
DUNKIN DONUTS                              2340 W 52ND ST   60609.0   

                                  Inspection Date        Inspection Type  \
DBA Name                                                                   
THE MECCA RESTAURANT                   03/14/2017                Canvass   
L & T CHINA FAST WOK INC.              03/14/2017                Canvass   
SCHNEIDER  SENIOR  APARTMENT           03/14/2017  Canvass Re-Inspection   
ECKHARDT CAFE                          03/14/2017                Canvass   
WING ZONE                              03/14/2017                Canvass   
ARBYS                                  03/14/2017                Canvass   
LAS ISLAS MARIAS                       03/14/2017                Canvass   
MARGARET'S                             03/14/2017                Canvass   
POPEYES FAMOUS FRIED CHICKEN           03/14/2017              Complaint   
PJ PIZZA COMPANY 1 DBA PAPA JOHNS      03/14/2017                Canvass   
DUNKIN DONUTS                          03/14/2017   Short Form Complaint   

                                              Results  \
DBA Name                                                
THE MECCA RESTAURANT               Pass w/ Conditions   
L & T CHINA FAST WOK INC.                        Pass   
SCHNEIDER  SENIOR  APARTMENT                     Pass   
ECKHARDT CAFE                                    Pass   
WING ZONE                             Out of Business   
ARBYS                                            Pass   
LAS ISLAS MARIAS                                 Pass   
MARGARET'S                                       Pass   
POPEYES FAMOUS FRIED CHICKEN       Pass w/ Conditions   
PJ PIZZA COMPANY 1 DBA PAPA JOHNS     Out of Business   
DUNKIN DONUTS                                    Pass   

                                                                          Violations  
DBA Name                                                                              
THE MECCA RESTAURANT               8. SANITIZING RINSE FOR EQUIPMENT AND UTENSILS...  
L & T CHINA FAST WOK INC.          33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...  
SCHNEIDER  SENIOR  APARTMENT       35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...  
ECKHARDT CAFE                      33. FOOD AND NON-FOOD CO

In [ ]:
#Select restaurants 100,1000 and 10000 along with columns 5,3, and 1.

df3.iloc[[100,1000,10000],[5,3,1]]

Inspection Type      Zip           Risk
DBA Name                                                          
TAQUERIA LA CANTERA                License  60608.0  Risk 1 (High)
PARK TAVERN CHICAGO              Complaint  60612.0  Risk 1 (High)
LITTLE VILLAGE HIGH SCHOOL         Canvass  60623.0  Risk 1 (High)

#QUESTION 5: STACK OVERFLOW DATASET

> Upload the dataset of stackoverflow_qa.csv.
1. Find all the questions that have exactly 5 answers.
2. Find all the questions that have less than 10 views.
3. Find where quest_name='Jason Strimpel'.
4. Do both 1 and 2.
5. Find where ans_name='Scott Boston' or ans_name='Ted Petrou' or ans_name='MaxU' or ans_name='unutbu'.



In [ ]:
df4=pd.read_csv('/stackoverflow_qa.csv',index_col=0)
df4

creationdate  score  viewcount  \
id                                                
5486226   2011-03-30 12:26:50      4       2113   
5515021   2011-04-01 14:50:44      8       7015   
5558607   2011-04-05 21:13:50      2       7392   
6467832   2011-06-24 12:31:45      9      13056   
7577546   2011-09-28 01:58:38      9       2488   
...                       ...    ...        ...   
47606711  2017-12-02 10:07:13      0         17   
47607549  2017-12-02 11:41:59     -1         41   
47609325  2017-12-02 15:16:26      0         33   
47609598  2017-12-02 15:45:40      2         18   
47611969  2017-12-02 19:59:09     -6         19   

                                                      title  answercount  \
id                                                                         
5486226                            Rolling median in python            3   
5515021        Compute a compounded return series in Python            3   
5558607         Sort a pandas DataMatrix in ascending order            2   
6467832   How to get the correlation between two timeser...            1   
7577546   Using pandas, how do I subsample a large DataF...            1   
...                                                     ...          ...   
47606711                              slow loop using panda            1   
47607549      Convert Numeric percentage values into String            1   
47609325  Filtering for criteria in Pandas Dataframe Python            2   
47609598  Python Multi index function with order preserv...            1   
47611969            Converting Pandas Dataframe to R object            0   

          commentcount  favoritecount      quest_name  quest_rep  \
id                                                                 
5486226              4            1.0         yueerhu      125.0   
5515021              6            7.0  Jason Strimpel     3301.0   
5558607              0            1.0  Jason Strimpel     3301.0   
6467832              0            7.0      user814005      117.0   
7577546              0            5.0    Uri Laserson      958.0   
...                ...            ...             ...        ...   
47606711             1            NaN            xxyy        3.0   
47607549             2            NaN           Ajeet        1.0   
47609325             4            NaN            NthA        1.0   
47609598             0            NaN         Fan LUO       13.0   
47611969             0            NaN   Soorya Paturi        1.0   

                 ans_name  ans_rep  
id                                  
5486226   Mike Pennington  26995.0  
5515021   Mike Pennington  26995.0  
5558607      Wes McKinney  43310.0  
6467832      Wes McKinney  43310.0  
7577546              HYRY  54137.0  
...                   ...      ...  
47606711        user32185    308.0  
47607549              NaN      NaN  
47609325              NaN      NaN  
47609598          erocoar    209.0  
47611969              NaN      NaN  

[56398 rows x 11 columns]

In [ ]:
#1. Find all the questions that have exactly 5 answers.
answer_count=df4['answercount']==5
df4[answer_count]



creationdate  score  viewcount  \
id                                                
10373660  2012-04-29 16:10:35    199     207980   
10791661  2012-05-29 00:06:52      7      12210   
10972410  2012-06-10 21:12:43     19      46428   
11391969  2012-07-09 09:04:33     44      27467   
11811392  2012-08-04 19:25:34     17      20051   
...                       ...    ...        ...   
47028601  2017-10-31 05:45:19      2         38   
46557074  2017-10-04 04:33:51      0         61   
46882557  2017-10-23 05:36:29      3         87   
47542980  2017-11-29 00:05:31      2         43   
47213771  2017-11-10 00:13:38      1        247   

                                                      title  answercount  \
id                                                                         
10373660    Converting a Pandas GroupBy object to DataFrame            5   
10791661  How do I discretize values in a pandas DataFra...            5   
10972410         pandas: combine two columns in a DataFrame            5   
11391969  How to group pandas DataFrame entries by date ...            5   
11811392  How to generate a list from a pandas DataFrame...            5   
...                                                     ...          ...   
47028601  how to remove 0's in a datacolumn in a datafra...            5   
46557074            Grouping similar values in a dictionary            5   
46882557             How to split columns faster in python?            5   
47542980           Pandas groupby - set of different values            5   
47213771                   column operation in csv [python]            5   

          commentcount  favoritecount       quest_name  quest_rep  \
id                                                                  
10373660             0           90.0          saveenr     2421.0   
10791661             0            3.0     Uri Laserson      958.0   
10972410             0            5.0             BFTM      895.0   
11391969             1           15.0    Boris Gorelik     9605.0   
11811392             0            6.0           turtle     1260.0   
...                ...            ...              ...        ...   
47028601             5            NaN              pyd      416.0   
46557074             0            NaN  ConstantLearner        3.0   
46882557             2            NaN         Steve Xu       23.0   
47542980             0            NaN   Baron Yugovich      260.0   
47213771            13            1.0             Alex       17.0   

                 ans_name   ans_rep  
id                                   
10373660     Wes McKinney   43310.0  
10791661           lbolla    4552.0  
10972410         BrenBarn  136870.0  
11391969     Wes McKinney   43310.0  
11811392         BrenBarn  136870.0  
...                   ...       ...  
47028601              NaN       NaN  
46557074  Jeremy McGibbon    1121.0  
46882557     Akshay Hegde   11362.0  
47542980          jezrael  186894.0  
47213771          Bharath   12877.0  

[296 rows x 11 columns]

In [ ]:
#2. Find all the questions that have less than 10 views.
view=df4['viewcount'] < 10
df4[view]

creationdate  score  viewcount  \
id                                                
26493306  2014-10-21 18:06:10      1          6   
33641540  2015-11-10 23:19:36      0          9   
40062672  2016-10-15 18:24:21     -1          9   
42538091  2017-03-01 17:20:37      0          9   
42080039  2017-02-07 01:13:30      0          8   
43271693  2017-04-07 07:04:19      0          9   
45069021  2017-07-12 23:22:49      1          9   
45212468  2017-07-20 10:43:55      0          9   
45890470  2017-08-25 23:16:57      0          7   
45991431  2017-08-31 23:26:20      0          9   
47091256  2017-11-03 08:20:58      0          8   
46628996  2017-10-08 08:22:26      0          7   
47208273  2017-11-09 17:38:49      0          6   
47254707  2017-11-12 22:26:52      0          9   
47611836  2017-12-02 19:44:00      0          8   
47126567  2017-11-05 20:58:17      0          9   
47440171  2017-11-22 16:58:49      0          8   
47461776  2017-11-23 18:45:23      0          8   
47550355  2017-11-29 10:20:18      0          9   
47477606  2017-11-24 17:09:18      0          5   
47553898  2017-11-29 13:23:17      2          9   
47548480  2017-11-29 08:46:06     -2          8   
47462671  2017-11-23 20:06:18      1          8   
47421513  2017-11-21 19:48:44      0          7   
47428726  2017-11-22 07:06:58      0          6   
47614866  2017-12-03 03:06:05      0          6   
47607315  2017-12-02 11:16:13      0          9   
47613361  2017-12-02 22:38:38      0          8   

                                                      title  answercount  \
id                                                                         
26493306  How to convert hierarchical DataFrame back fro...            0   
33641540  Joining Dataframes in Pandas deletes an existi...            1   
40062672  Replace one or more sub-strings from multiple ...            1   
42538091                      Saving box plot pandas python            0   
42080039  pandas: count the non-duplicated elements when...            1   
43271693                       Pandas Unsuccessfully Modify            1   
45069021  Can ask for strides of k subsequent items from...            1   
45212468                       Pandas reads partial content            0   
45890470  result of pandas.PeriodIndex(astype(str)) in p...            1   
45991431  Check for excel file on a url link via while l...            0   
47091256  Unifying columns in the same Pandas dataframe ...            1   
46628996  Trying to aggregate two columns of values into...            0   
47208273     Pandas SettingWithCopyWarning with to_datetime            0   
47254707  CSV download from Github link gives tokenizing...            1   
47611836  pandas: different plot x-values when plotting ...            0   
47126567             Expanding Int64 data type in dataframe            0   
47440171  Multi-index and time-stamps not recognised in ...            0   
47461776  how to drop duplicates in pandas when entries ...            1   
47550355  pandas HTML rendering of multi-index changes w...            0   
47477606  Plotly- shading time series regions based on a...            0   
47553898  Pandas: Delete duplicated items in a specific ...            1   
47548480  how to store the Pandas nunique value of age i...            0   
47462671     Create column that makes summation to a scalar            1   
47421513  Converting CSV to sqlite3 table in pandas - "8...            1   
47428726               How to link a python file with libm?            0   
47614866  How to convert a List of lists with nested dic...            0   
47607315  ModuleNotFoundError: No module named 'pandas._...            0   
47613361  How to remove duplicate markers in gmaps in pa...            0   

          commentcount  favoritecount          quest_name  quest_rep ans_name  \
id                                                                              
26493306             2            1.0      

In [ ]:
#3. Find where quest_name='Jason Strimpel'.
res=df4['quest_name']=='Jason Strimpel'
df4[res]

creationdate  score  viewcount  \
id                                                
5515021   2011-04-01 14:50:44      8       7015   
5558607   2011-04-05 21:13:50      2       7392   
14509517  2013-01-24 19:49:25      1        962   
18065948  2013-08-05 19:17:03      1        255   
17623019  2013-07-12 19:55:49      4        746   
17576615  2013-07-10 17:00:27      3       6337   
14940948  2013-02-18 16:33:35      3        515   
14941097  2013-02-18 16:41:15     28      36875   
15751283  2013-04-01 20:28:44      7       4610   
20426287  2013-12-06 14:26:39      0        131   
25315873  2014-08-14 19:12:55      0        148   
27640202  2014-12-24 17:12:44      4        877   
27322502  2014-12-05 18:35:12      1        219   
35593337  2016-02-24 04:33:58      2        668   
38261486  2016-07-08 07:48:17      1         74   
39485160  2016-09-14 07:50:20      0         80   
41777149  2017-01-21 08:14:51      1        298   
41907210  2017-01-28 06:59:34      1         64   

                                                      title  answercount  \
id                                                                         
5515021        Compute a compounded return series in Python            3   
5558607         Sort a pandas DataMatrix in ascending order            2   
14509517  MySQL v. SQLite for Python based financial web...            3   
18065948              Get index where both rows are not NaN            1   
17623019     NaNs in pandas.DataFrame not printing to Excel            1   
17576615  Pandas date_range from DatetimeIndex to Date f...            1   
14940948  Using pandas.ols on multiple dependent variabl...            2   
14941097                Selecting pandas column by location            5   
15751283  Converting a pandas MultiIndex DataFrame from ...            1   
20426287  get_forward_data() deprecated warning in panda...            1   
25315873                   Map List of Tuples to New Column            2   
27640202  Fill multi-index Pandas DataFrame with interpo...            1   
27322502              Row and column indexes of True values            1   
35593337        Fill pandas DataFrame nans with index value            3   
38261486          Sorting a Pandas Pivot Containing Strings            1   
39485160  Python CGI Script "Cannot allocate memory" Imp...            1   
41777149  Insert Timezone Aware datetime64[ns] into MySQ...            1   
41907210  How to resort a MultiIndex DataFrame by second...            1   

          commentcount  favoritecount      quest_name  quest_rep  \
id                                                                 
5515021              6            7.0  Jason Strimpel     3301.0   
5558607              0            1.0  Jason Strimpel     3301.0   
14509517             0            NaN  Jason Strimpel     3301.0   
18065948             0            1.0  Jason Strimpel     3301.0   
17623019             0            NaN  Jason Strimpel     3301.0   
17576615             4            NaN  Jason Strimpel     3301.0   
14940948             1            NaN  Jason Strimpel     3301.0   
14941097             1            5.0  Jason Strimpel     3301.0   
15751283             0            3.0  Jason Strimpel     3301.0   
20426287             2            NaN  Jason Strimpel     3301.0   
25315873             1            NaN  Jason Strimpel     3301.0   
27640202             0            1.0  Jason Strimpel     3301.0   
27322502             0            1.0  Jason Strimpel     3301.0   
35593337             0            NaN  Jason Strimpel     3301.0   
38261486             7            NaN  Jason Strimpel     3301.0   
39485160             0            NaN  Jason Strimpel     3301.0   
41777149             0            0.0  Jason Strimpel     3301.0   
41907210             5            NaN  Jason Strimpel     3301.0   

                  ans_name   ans_rep  
id                                    
5515021    Mike Pennington   26995.0

In [ ]:
#4. Do both 1 and 2.
Final=answer_count & view
df4[Final]


Empty DataFrame
Columns: [creationdate, score, viewcount, title, answercount, commentcount, favoritecount, quest_name, quest_rep, ans_name, ans_rep]
Index: []

In [ ]:
 #5. Find where ans_name='Scott Boston' or ans_name='Ted Petrou' or ans_name='MaxU' or ans_name='unutbu'.
A=df4['ans_name']=='Scott Boston'
B=df4['ans_name']=='Ted Petrou'
C=df4['ans_name']=='MaxU'
D=df4['ans_name']=='unutbu'

Z = A | B | C | D
df4[Z]

creationdate  score  viewcount  \
id                                                
10665889  2012-05-19 14:11:42    144     179896   
13385860  2012-11-14 19:25:28     29      31712   
13446480  2012-11-19 01:20:07     18       7969   
13460889  2012-11-19 19:39:06      8       3168   
13653030  2012-11-30 20:54:35      6      11798   
...                       ...    ...        ...   
47491733  2017-11-26 00:03:50      0         36   
47437109  2017-11-22 14:26:13     -2         23   
47498619  2017-11-26 16:50:51      3         43   
47516326  2017-11-27 17:09:21      2         27   
47581808  2017-11-30 20:12:18      3         27   

                                                      title  answercount  \
id                                                                         
10665889   How to take column-slices of dataframe in pandas            7   
13385860  How can I remove extra whitespace from strings...            6   
13446480  Python Pandas: remove entries based on the num...            4   
13460889  How to redirect all methods of a contained cla...            2   
13653030  How do I Pass a List of Series to a Pandas Dat...            5   
...                                                     ...          ...   
47491733     Getting rows where columns have certain values            1   
47437109  how to write dataframe data likes '0012' to cs...            1   
47498619  Why is pandas.dataframe.groupby faster when as...            1   
47516326  Pandas DataFrame Issue. Don't know how to clea...            1   
47581808   Fill Down a value in Pandas once it has occurred            1   

          commentcount  favoritecount     quest_name  quest_rep      ans_name  \
id                                                                              
10665889             3           65.0            cpa      988.0    Ted Petrou   
13385860             0           17.0          mpjan      530.0        unutbu   
13446480             1            7.0      sashkello     8714.0        unutbu   
13460889             4            5.0          Yariv     5013.0        unutbu   
13653030             1            1.0       rhaskett      323.0        unutbu   
...                ...            ...            ...        ...           ...   
47491733             0            NaN          Katie       20.0          MaxU   
47437109             2            NaN      Uncle LAU        8.0  Scott Boston   
47498619             0            1.0        JonB451       20.0        unutbu   
47516326             4            0.0  FrancoFranchi       13.0  Scott Boston   
47581808             1            0.0   Dani Freidus       18.0  Scott Boston   

           ans_rep  
id                  
10665889   10426.0  
13385860  464745.0  
13446480  464745.0  
13460889  464745.0  
13653030  464745.0  
...            ...  
47491733   83732.0  
47437109   23611.0  
47498619  464745.0  
47516326   23611.0  
47581808   23611.0  

[3253 rows x 11 columns]

ASSIGNING A SUBSET OF ROWS AND COLUMNS

In [ ]:
ds=pd.read_csv('/sample_data.csv',index_col=0)
ds

state  color    food  age  height  score
Jane         NY   blue   Steak   30     165    4.6
Niko         TX  green    Lamb    2      70    8.3
Aaron        FL    red   Mango   12     120    9.0
Penelope     AL  white   Apple    4      80    3.3
Dean         AK   gray  Cheese   32     180    1.8
Christina    TX  black   Melon   33     172    9.5
Cornelia     TX    red   Beans   69     150    2.2

In [ ]:
ds.loc[['Niko','Aaron','Penelope'],'food'] = [3,6,4]
ds

state  color    food  age  height  score
Jane         NY   blue   Steak   30     165    4.6
Niko         TX  green       3    2      70    8.3
Aaron        FL    red       6   12     120    9.0
Penelope     AL  white       4    4      80    3.3
Dean         AK   gray  Cheese   32     180    1.8
Christina    TX  black   Melon   33     172    9.5
Cornelia     TX    red   Beans   69     150    2.2

In [ ]:
ds.iloc[3:6,5]=90
ds

state  color    food  age  height  score
Jane         NY   blue   Steak   30     165    4.6
Niko         TX  green       3    2      70    8.3
Aaron        FL    red       6   12     120    9.0
Penelope     AL  white       4    4      80   90.0
Dean         AK   gray  Cheese   32     180   90.0
Christina    TX  black   Melon   33     172   90.0
Cornelia     TX    red   Beans   69     150    2.2

In [ ]:
ds.loc['Dean',['age','height','score']] = [50,100,30]
ds

state  color    food  age  height  score
Jane         NY   blue   Steak   30     165    4.6
Niko         TX  green       3    2      70    8.3
Aaron        FL    red       6   12     120    9.0
Penelope     AL  white       4    4      80   90.0
Dean         AK   gray  Cheese   50     100   30.0
Christina    TX  black   Melon   33     172   90.0
Cornelia     TX    red   Beans   69     150    2.2

In [ ]:
ds.loc[ds['height'] >100,'score']=65
ds

state  color    food  age  height  score
Jane         NY   blue   Steak   30     165   65.0
Niko         TX  green       3    2      70    8.3
Aaron        FL    red       6   12     120   65.0
Penelope     AL  white       4    4      80   90.0
Dean         AK   gray  Cheese   50     100   30.0
Christina    TX  black   Melon   33     172   65.0
Cornelia     TX    red   Beans   69     150   65.0

In [ ]:
x=ds.groupby('score').sum() #groupby()
x

<ipython-input-364-e862fe8517b5>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  x=ds.groupby('score').sum() #groupby()


age  height
score             
8.3      2      70
30.0    50     100
65.0   144     607
90.0     4      80